name: ArchitecturePractice
options:
    bundleIdPrefix: Toshiki-Yanagimoto.ArchitecturePractice
settings:
  base:
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
targets:
  ArchitecturePractice:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: ArchitecturePractice
    schemes:
        ArchitecturePractice:
        testTargetName: ArchitecturePracticeTests
    preBuildScripts:
      - path: ./Scripts/before-compile.sh
        name: before-compile
        shell: "/bin/bash"

  ArchitecturePracticeTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources: ArchitecturePracticeTests
    dependencies:
      - target: ArchitecturePractice

  ArchitecturePracticeUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "14.0"
    sources: ArchitecturePracticeUITests
    dependencies:
      - target: ArchitecturePractice
